import{S as M,i as c,a as C}from"./assets/vendor-BzajH6aU.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const d of i.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function l(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function o(e){if(e.ep)return;e.ep=!0;const i=l(e);fetch(e.href,i)}})();const y=document.querySelector(".loader"),n=document.querySelector(".load-more-js"),h=document.querySelector(".load-more-loader");function L(r){const t=document.querySelector(".gallery");r.totalHits>0?(t.insertAdjacentHTML("beforeend",r.hits.map(o=>`<li class="gallery-item">
          <a class="gallery-link" href="${o.largeImageURL}">
            <img
              class="gallery-image"
              src="${o.webformatURL}"
              data-source="${o.largeImageURL}"
              alt="${o.tags}"
            />
          </a>          
          <ul class='gallery-list-details'>
            <li class='gallery-item-details'><p class='gallery-item-text'>Likes</p><p class="item-value">${o.likes}</p></li>
            <li class='gallery-item-details'><p class='gallery-item-text'>Views</p><p class="item-value">${o.views}</p></li>
            <li class='gallery-item-details'><p class='gallery-item-text'>Comments</p><p class="item-value">${o.comments}</p></li>
            <li class='gallery-item-details'><p class='gallery-item-text'>Downloads</p><p class="item-value">${o.downloads}</p></li>
          </ul>          
        </li>`).join("")),new M(".gallery a",{overlayOpacity:.9,captionsData:"alt",captionDelay:250}).refresh()):(m(),t.innerHTML="")}function S(){y.classList.remove("hidden")}function w(){y.classList.add("hidden")}function O(){h.classList.remove("hidden")}function x(){h.classList.add("hidden")}function b(){n.classList.remove("hidden")}function g(){n.classList.add("hidden")}function q(){c.show({title:"Hello",titleColor:"#000",message:"Welcome to our Website!",messageColor:"#000",position:"topRight",color:"#09f",icon:"fas fa-bell",timeout:4e3})}function m(){c.error({title:"Error",titleColor:"#fff",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",color:"#ef4040",position:"topRight",icon:"fas fa-exclamation-triangle",transitionIn:"flipInX",transitionOut:"flipOutX",timeout:3e3})}function R(){c.error({title:"Error",titleColor:"#fff",message:"Please fill in the search images field",messageColor:"#fff",color:"#ef4040",position:"topRight",icon:"fas fa-exclamation-triangle",transitionIn:"flipInX",transitionOut:"flipOutX",timeout:3e3})}function E(){c.warning({title:"Caution",titleColor:"#000",message:"We are sorry, but you have reached the end of search results.",messageColor:"#000",position:"bottomCenter",color:"yellow",icon:"fas fa-exclamation-circle",timeout:4e3})}function I(){c.warning({title:"Caution",titleColor:"#000",message:"Something went wrong, please try again",messageColor:"#000",position:"topRight",color:"orange",icon:"fas fa-exclamation-circle",timeout:4e3})}async function v(r,t=1){const l="46906317-bfa2c9d7c6708063f650b6890",o="https://pixabay.com/api/";try{return(await C(`${o}`,{params:{key:l,q:r,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(e){throw I(),new Error(e.statusText)}}document.addEventListener("DOMContentLoaded",q);const u=document.querySelector(".form"),$=document.querySelector(".gallery"),p=u.querySelector('button[type="submit"]');let a=1,s="",f="";n.addEventListener("click",H);u.addEventListener("submit",async r=>{if(r.preventDefault(),s=r.target.elements.search.value.trim(),s&&s!==f){f=s,a=1,S(),$.innerHTML="",p.disabled=!0;try{const t=await v(s,a);u.reset(),L(t),a<Math.ceil(t.totalHits/15)&&b()}catch(t){console.error(t),m()}finally{w(),p.disabled=!1}}else R()});async function H(){if(s===f){n.disabled=!0,g(),O(),a++;try{const r=await v(s,a);L(r);const t=Math.ceil(r.totalHits/15);a>=t?(g(),E()):b();const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:o*2,behavior:"smooth"})}catch{m()}finally{w(),x(),n.disabled=!1}}}
//# sourceMappingURL=index.js.map
